### PR TITLE
Update to revised artifact/version scheme

### PR DESCRIPTION
**Pull request by kenfinnigan**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
@sberyozkin can you take a look and approve?

**Comment by sberyozkin** [comment]
@kenfinnigan, I was considering if we should do a quick release first with some immediate fixes and get them into Thorntail. @MikeEdgar  resolved a bug in #113 which can be of the immediate interest to Thorntail. What do you think ? @Ladicek,  FYI

**Comment by Ladicek** [comment]
I don't mind either way.

**Comment by sberyozkin** [comment]
@kenfinnigan @Ladicek well, we can that fix in with the updated versioning scheme as well :-), but I'm not sure if it can affect the productiization effort ?

**Pull request merged**
