### PR TITLE
Add Github Action build.

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hey @radcortez Is it supposed to fail in semaphore and as such a failure can be ignored ?

**Comment by radcortez** [comment]
It seems the VM just randomly crashed running the TCK:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project smallrye-jwt-tck: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/runner/smallrye-jwt/testsuite/tck/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/runner/smallrye-jwt/testsuite/tck && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/runner/smallrye-jwt/testsuite/tck/target/jacoco.exec,append=true -jar /home/runner/smallrye-jwt/testsuite/tck/target/surefire/surefirebooter6433813114071614163.jar /home/runner/smallrye-jwt/testsuite/tck/target/surefire 2020-03-20T11-32-18_985-jvmRun1 surefire1462926992458416822tmp surefire_2263795156060197161tmp
[ERROR] Process Exit Code: 0
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/runner/smallrye-jwt/testsuite/tck && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/runner/smallrye-jwt/testsuite/tck/target/jacoco.exec,append=true -jar /home/runner/smallrye-jwt/testsuite/tck/target/surefire/surefirebooter6433813114071614163.jar /home/runner/smallrye-jwt/testsuite/tck/target/surefire 2020-03-20T11-32-18_985-jvmRun1 surefire1462926992458416822tmp surefire_2263795156060197161tmp
[ERROR] Process Exit Code: 0
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :smallrye-jwt-tck
```

I don't think the issue is caused by this PR. I've seen reports of other people complain of random crashed in Semaphore before. That is one of the reason why we want to move away from it.

I've trigger a new build to see what happens.

**Comment by sberyozkin** [comment]
@radcortez Cool, so from now on, what happens, when 2.1.2 release has to be done, it has been discussed at length in the forum, but can you please summarize ?

**Comment by radcortez** [comment]
I haven't pushed yet the release workflows. I've documented the process here:
https://github.com/smallrye/smallrye-parent/wiki/SmallRye-Release-Process

If you are happy with it, I can push the rest of the configuration and we can try it to do a release when needed. I've already done it for SmallRye Config.

**Comment by sberyozkin** [comment]
@radcortez OK, thanks, let me merge this one first

**Comment by radcortez** [comment]
Yes, so this is just build only. Releases are still done by Semaphore.

We can just do a gradual shift.

**Pull request merged**
