### PR TITLE
Move the JAX-RS related code into smallrye-jwt-jaxrs

### LINKED ISSUE #332: Improve jwt-auth modularization before 3.0.0 release
The old `implementation` module has just been split on the master branch into `common` , `jwt-build` and `jwt-auth` (which is effectively the old `implementation` minus the common utility and JWT builder API). 
`jwt-auth` still depends on `jwt-build` to keep the existing expectations and it also ships the JAX-RS code which is not used by all the integrators.
The proposal is to modularize `jwt-auth` further before `3.0.0` (MP JWT 1.2) is released :
- move the JAX-RS code into a new `jwt-jaxrs` module which will depend on `jwt-auth`
- drop `smallrye-jwt-build` dependency and let users add it if it is needed (though if we can expect the builder API be eventually standardized then perhaps it would be better to keep this dependency but the users  can now easily exclude it if they don't use the builder API - this looks like a better option - otheriwise if we drop it now and then decide to add back then it would be a bit of a mess :-) )

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #332

This PR tries to improve the modularization further and moves the JAX-RS related code into its own module `smallrye-jwt-jaxrs` - for example, in Quarkus, the JAX-RS part is not used.
My only tiny concern here is that in `SmallRyeJWTAuthCDIExtension` the JAX-RS filter is now loaded reflectively - this is fine for the TCK tests though.
This PR targets the `mpjwt12` branch.
Lets check it early next year :-)

### CODE REVIEW

**Review by MikeEdgar — APPROVED** [review]

**Comment by sberyozkin** [comment]
@MikeEdgar thanks, and happy holidays; I'll also wait for Roberto and especially for Darran to review as he may be using some of that code, cheers

**Comment by radcortez** [comment]
> My only tiny concern here is that in `SmallRyeJWTAuthCDIExtension` the JAX-RS filter is now loaded reflectively - this is fine for the TCK tests though.

We can probably mode the CDI Extension to its own module as well: `jwt-cdi`. I've done that with SR Config. Quarkus does not need the extension.

**Review by radcortez — APPROVED** [review]

**Comment by sberyozkin** [comment]
@radcortez Yeah, that can be further optimized. I'll ping Darran now to check too

**Review by darranl — APPROVED** [review]
Adding an approval, we don't use the JAX-RS integration ourselves within WildFly so will be good to separate.

**Comment by sberyozkin** [comment]
Thanks all

**Pull request merged**
