### PR TITLE
Formatter Maven Plugin changes.

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by darranl** [comment]
If there is any way within CI it would help if PRs could fail if the build results in code being reformatted to stop these slipping through.

**Comment by radcortez** [comment]
I think so. We can run this goal instead in the CI:
https://code.revelc.net/formatter-maven-plugin/validate-mojo.html

And fail the build. I'll give it a try.

**Comment by radcortez** [comment]
I'll be merging this, because I'm getting annoyed of file changes not related with the work I'm doing :)

**Comment by radcortez** [comment]
@darranl The check to fail the CI if the formatter fails is already in the CI as well, so hopefully this shouldn't happen anymore.

**Pull request merged**
