### PR TITLE
Switch to smallrye-parent 39

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by radcortez** [comment]
@sberyozkin I ended up moving JUnit 4 to 5 as well

**Comment by sberyozkin** [comment]
Hey @radcortez Thanks a million for taking care of all of the updates, I'd otherwise have to spent another week on it :-). I'll have a quick look a little bit later today just to make sure I follow what has changed and merge then, cheers

**Comment by sberyozkin** [comment]
LGTM, I was not able to find an Approve button, strangely.
Thanks Roberto for this PR

**Comment by radcortez** [comment]
> LGTM, I was not able to find an Approve button, strangely.

Because you are the author of the PR :)

**Pull request merged**
