### PR TITLE
Add the configuration section to README

### LINKED ISSUE #106: Improve the documentation
smallrye-jwt configuration has been significantly enhanced. The documentation needs to reflect it

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #106

### CODE REVIEW

**Comment by MikeEdgar** [comment]
@sberyozkin - I noticed there are a few missing and some possible typos.

* `smallrye.jwt.time-to-live` is missing
* `smallrye.jwt.token.kid` is missing
* `smallrye.jwt.whitelist.algorithms` is missing (but deprecated anyway)
* `smallrye.jwt.path.groups-separator` should instead be `smallrye.jwt.groups-separator`
* `smallrye.jwt.jwk.refresh-interval` should be `smallrye.jwt.jwks.refresh-interval`
* `smallrye.jwt.verify.audience` should be `smallrye.jwt.verify.aud`
* `mp.jwt.verify.requireiss` is a supported option that is not listed. This one isn't in the spec in spite of the name

**Comment by sberyozkin** [comment]
@MikeEdgar Thanks, yes I deliberately did not mention `smallrye.jwt.whitelist.algorithms`. And `mp.jwt.verify.requireiss` is indeed a bit confusing, it is not in the spec and I'm not sure it is a good idea to skip verifying the issuer, every token has an issuer, it was probably proposed to make it simpler for someone to test :-), so I'd like to avoid mentioning these 2 properties

**Comment by sberyozkin** [comment]
@MikeEdgar Hopefully it is all good now :-), going to fix the typos in the Quarkus guide next :-)

**Comment by sberyozkin** [comment]
@MikeEdgar Hi Mike, my Quarkus colleagues have spotted it when I was fixing the typos in the Quarkus docs after your review :-). I was a bit unfocused, sorry :-).
Thanks

**Pull request merged**
