### PR TITLE
Release SmallRye JWT 2.4.4

### PR DESCRIPTION
**Pull request by sberyozkin**
Please see the [commits](https://github.com/smallrye/smallrye-jwt/compare/fe8e21b...ad308fb) and the [affected source](https://github.com/smallrye/smallrye-jwt/compare/fe8e21b..ad308fb).

### CODE REVIEW

**Review by darranl — APPROVED** [review]
One thing that might be useful in these PRs is add a link to the description that shows the changes between the last release and this release just to double check the content.

**Comment by sberyozkin** [comment]
@darranl sounds good, thanks, I've updated the description - please double check, I can merge this PR a bit later today

**Comment by darranl** [comment]
No major issues although maybe in future it would be good to be more cautious about the removal of items that could be used in a micro release e.g. "ECDH_ES_A28KW("ECDH-ES+128KW")," - although this enumeration is obviously wrong users could have developed  code against it so upgrading to 2.4.4 would break that code.

**Comment by sberyozkin** [comment]
@darranl Yes, it is indeed a bad typo so I'm nearly 100% sure the users haven't tried it :-) so I was considering it as a bug fix, but such changes would have to be reflected better in the release version. 

I'm going to rename the `2.4.x` branch to `2.x` for it to accommodate the minor releases as well going forward.
Cheers

**Comment by radcortez** [comment]
> One thing that might be useful in these PRs is add a link to the description that shows the changes between the last release and this release just to double check the content.

We can certainly make the bot to add the links.

**Pull request merged**
