### PR TITLE
Fix KeyEncryptionAlgorithm ECDH-ES typos

### PR DESCRIPTION
**Pull request by giotsintsadze**
Please check if it satisfies your requirements.

### CODE REVIEW

**Review by Skyllarr — APPROVED** [review]

**Comment by Skyllarr** [comment]
@giotsintsadze Thanks! Please rename the commit to be more informative and link the issue in the description

**Comment by giotsintsadze** [comment]
Hello, here is my new commit, https://github.com/giotsintsadze/smallrye-jwt/commit/4cb9c39f62cb5a2207066d04e221774da5e64d58

i hope it will satisfies the current request

**Comment by Skyllarr** [comment]
Hi @giotsintsadze , there is currently 3 commits in this PR. Please squash them into a single commit. Thank you!

**Comment by Skyllarr** [comment]
@giotsintsadze You can get a single commit by running these git commands on your typo-fix branch:

```
git reset --soft HEAD~2
git commit -m "Fix typos in KeyEncryptionAlgorithm ECDH-ES+* enums (#737)"
```

and then force pushing to your remote. Let me know if you have any questions about this. Thanks

**Comment by giotsintsadze** [comment]
Hey sorry for late, please check if it is done correctly

**Comment by sberyozkin** [comment]
@giotsintsadze Thanks for the PR. Looks like something has gone wrong now with the commit history, as it now shows 5 commits. At this stage I'd consider creating a new branch, and cherry-picking https://github.com/smallrye/smallrye-jwt/pull/741/commits/4cb9c39f62cb5a2207066d04e221774da5e64d58, `git cherry-pick 4cb9c39f62cb5a2207066d04e221774da5e64d58`, or simply add the same update again as it is literally a 2 characters change. 
@Skyllarr, are you OK with either of these plans ?

**Comment by Skyllarr** [comment]
> @giotsintsadze Thanks for the PR. Looks like something has gone wrong now with the commit history, as it now shows 5 commits. At this stage I'd consider creating a new branch, and cherry-picking [4cb9c39](https://github.com/smallrye/smallrye-jwt/commit/4cb9c39f62cb5a2207066d04e221774da5e64d58), `git cherry-pick 4cb9c39f62cb5a2207066d04e221774da5e64d58`, or simply add the same update again as it is literally a 2 characters change. @Skyllarr, are you OK with either of these plans ?

 @sberyozkin Yes that sounds like a good approach now,  @giotsintsadze if you decide to submit a new PR you can close this one. Thanks!

**Pull request closed without merging**
